---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsecops-bg

resources:
  - ../../base/blue-green

images:
  - name: aimocont2020/devsecops-demo
    newTag: "51612ec3ecbb"

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: devsecops-demo-bg
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
