---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devsecops
resources:
  - ../../base
images:
  - name: aimocont2020/devsecops-demo
    newTag: "568343be55fb"
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: devsecops-demo
    patch: |-
      - op: add
        path: /spec/replicas
        value: 4
