---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: devsecops-demo

spec:
  selector:
    matchLabels:
      app: devsecops-demo

  template:
    metadata:
      labels:
        app: devsecops-demo

    spec:
      containers:
        - name: devsecops-demo
          image: aimocont2020/devsecops-demo
          ports:
            - containerPort: 8080

  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {}

        - setWeight: 50
        - pause: {}

        - setWeight: 100
